CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX idx_projects_user ON projects (user_id);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO',
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    due_date DATE,
    CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE RESTRICT,
    CONSTRAINT ck_tasks_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT ck_tasks_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);
CREATE INDEX idx_tasks_project ON tasks (project_id);

CREATE TABLE focus_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP(6) WITH TIME ZONE,
    paused_at TIMESTAMP(6) WITH TIME ZONE,
    total_paused_seconds BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_focus_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_focus_sessions_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE RESTRICT,
    CONSTRAINT ck_focus_sessions_state CHECK (
        (status = 'RUNNING' AND ended_at IS NULL AND paused_at IS NULL) OR
        (status = 'PAUSED' AND ended_at IS NULL AND paused_at IS NOT NULL) OR
        (status = 'COMPLETED' AND ended_at IS NOT NULL AND paused_at IS NULL)
    ),
    CONSTRAINT ck_focus_sessions_paused CHECK (total_paused_seconds >= 0),
    CONSTRAINT ck_focus_sessions_pause_time CHECK (paused_at IS NULL OR paused_at >= started_at),
    CONSTRAINT ck_focus_sessions_end_time CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT ck_focus_sessions_duration CHECK (
        ended_at IS NULL OR FLOOR(EXTRACT(EPOCH FROM (ended_at - started_at))) >= total_paused_seconds
    )
);
CREATE INDEX idx_focus_sessions_user ON focus_sessions (user_id);
CREATE INDEX idx_focus_sessions_task ON focus_sessions (task_id);
